### ISSUE TITLE
Use an extension type to manage the GEOSGeometry pointers

### ISSUE THREAD

**Issue by caspervdw** [caspervdw/pygeos#1]
Following up on https://github.com/Toblerity/Shapely/issues/501

In C, a python object is just a pointer (PyObject *) to a struct which includes some standard members, but may include additional ones. Cython static attributes end up there. Accessing these from C does not include the overhead. If I look at https://docs.python.org/3/extending/newtypes_tutorial.html, I could create an (immutable) extension type with pointer as additional attribute and with a custom tp_dealloc that calls the GEOSDestroy_r.

The advantage would be that we leverage python/numpy's reference counting and on the garbage collector to deallocate stuff.

**Comment by caspervdw** [comment]
@jorisvandenbossche @mrocklin

**Comment by mrocklin** [comment]
Getting GC would be a great help.  I'm curious though, what is the cost of creating and managing Python objects, even in C.  I would expect there to be some non-trivial additional costs.  I would be happy to be wrong though.

**Comment by caspervdw** [comment]
I have some first results in https://github.com/caspervdw/pygeos/tree/extensiontype

There seems to be no additional overhead when putting the GEOSGeometry pointer in a static attribute of the object!

**Comment by caspervdw** [comment]
Closing through #2
