### ISSUE TITLE
Investigate PyArray_RegisterDataType to register a custom geometry dtype

### ISSUE THREAD

**Issue by caspervdw** [caspervdw/pygeos#11]

**Comment by jorisvandenbossche** [comment]
I was wondering if this would help with a small performance overhead of needing to check that each element is a GeometryObject. 

Assuming such a dtype is possible, then that would allow us to ensure that each element in the array is Geometry object, and inside the loop this does not need to be checked. I think this is a nicer user experience, and also enables some performance improvements.

Eg with a "contains(polygon, 1 million points)" timing, I see it go down from 55ms to 43ms by disabling the `!PyObject_IsInstance` check branch in `get_geom`. A modest but still nice improvement.

When going this route, and in case we want "missing" values, we need a sentinel for this that is a Geometry object, but I suppose we can use a GeometryObject with a NULL pointer for this.

Some examples in the wild:

- https://github.com/stefanv/teaching/blob/master/2013_scipy_austin_dive_into_numpy/slides/custom_dtypes.md
- https://github.com/alexhsamuel/ora
- https://github.com/moble/quaternion

**Comment by jorisvandenbossche** [comment]
Another aspect that could be enabled by this is that accessing items from the array gives a scalar Geometry with more complete functionality (eg shapely scalar, depending on the relationship with shapely), but keep the "bare" Geometry object stored in the array. This can give a memory benefit:

```
In [12]: g = pygeos.box(0, 0, 1, 1) 

In [13]: g2 = shapely.geometry.box(0, 0, 1, 1)

In [14]: sys.getsizeof(g) 
Out[14]: 24

In [15]: sys.getsizeof(g2)
Out[15]: 56
```

**Comment by caspervdw** [comment]
Continuing on #34
