### ISSUE TITLE
get_geometry is not safe (segfaults on out of bound index)

### ISSUE THREAD

**Issue by jorisvandenbossche** [caspervdw/pygeos#26]
A small issue I noticed, doing a `pygeos.get_geometry(arr, i)` crashes when `i` is out of bounds.
Not sure on what level this can be checked, but ideally (IMO), a python function should never crash but raise an error.

**Comment by caspervdw** [comment]
Agreed, this should be looked into.

**Comment by caspervdw** [comment]
@jorisvandenbossche  I was looking at this issue. Currently, three functions suffer from it: `get_geometry`, `get_interior_ring`, and `get_point`. These are for collections, polygons and linestrings respectively.

Would it make sense to make a single function out of this (`get_element`) that identifies the geometry type, does the bounds checking using the correct function, and gets the element using the correct function?
