### ISSUE TITLE
Handling of missing geometries

### ISSUE THREAD

**Issue by jorisvandenbossche** [caspervdw/pygeos#28]
Related to the discussion in https://github.com/geopandas/geopandas/pull/1062

Currently, missing geometries (np.nan, None), are handled similarly to empty geometries:

```
In [1]: import pygeos

In [4]: a = np.array([None, np.nan, pygeos.Geometry("POLYGON EMPTY"), pygeos.box(0, 0, 1, 1)])

In [5]: a
Out[5]: 
array([None, nan, <pygeos.Empty>,
       <pygeos.Geometry POLYGON ((1 0, 1 1, 0 1, 0 0, 1 0))>],
      dtype=object)

In [6]: pygeos.is_empty(a)
Out[6]: array([ True,  True,  True, False])
```

But I think, based on your comment in https://github.com/geopandas/geopandas/pull/1062, that it is the idea to separate both concepts?

But also then, there are still some aspects that need to be decided. Quoting @caspervdw from the linked geopandas issue:

> I am curious about how to deal with missing values in the various GEOS functions, especially for:
>
> - predicates (unary and binary)
> - integer-returning functions (like “get_num_points”
> - aggregation functions (should “create_collection” skip or propagate NaN?)
>
> Is it an idea to implement something like NaG (not-a-geometry)?

**Comment by caspervdw** [comment]
Let's continue this at #36

**Comment by jorisvandenbossche** [comment]
(small note, typically in the projects I am involved in, we leave the issue open until it is actually fixed, i.e. the PR merged. And by putting "closes #xxx" in the PR, this is done automatically for you by github)
