### ISSUE TITLE
Handling of empty geometries

### ISSUE THREAD

**Issue by jorisvandenbossche** [caspervdw/pygeos#29]
Related to https://github.com/caspervdw/pygeos/issues/28 about missing values and the discussion in https://github.com/geopandas/geopandas/pull/1062. 
But even when we split missing values as a separate concept, there are still some potential pitfalls and corner cases regarding empty geometries itself (as I experienced on that geopandas PR).

Currently, there is a `pygeos.Empty` "singleton" defined as an empty GeometryCollection:

https://github.com/caspervdw/pygeos/blob/de5ed5c5f0a55bf471531e328d1a1b0476bcafd2/src/ufuncs.c#L1213-L1216

However, GEOS has also the notion of eg empty polygons. 
See https://github.com/Toblerity/Shapely/issues/742 for some discussion in Shapely about this.

Having a more consistent empty handling as Shapely would be nice, but we might need to consider the potential consequences. Eg I remember that some file formats are strict regarding only allowing a single geometry type in a single column (eg only (multi)polygons). It might be that then an empty geometrycollection instead of empty polygon can give problems (purely hypothetical, didn't check it).

**Comment by caspervdw** [comment]
This is a hard one. My guess is that this is indeed a consideration having to do with fixed-type file or table formats. Although there is only one kind of empty geometry (as in “the empty set”).

We don’t have that problem in pygeos/geopandas as we only have one Geometry type and don’t fix subtypes.

I think a better design would be:
- make a “Singleton” not-a-geometry object (that is in fact a pygeos.Geometry)
- allow empty geometries to exist in any type, not as singletons

**Comment by jorisvandenbossche** [comment]
> allow empty geometries to exist in any type, not as singletons

So basically this is: don't have the current empty singleton, and just use whatever GEOS returns for a certain operation / construction?

**Comment by caspervdw** [comment]
Let's continue this at #36
