### ISSUE TITLE
Get and set coordinates in bulk

### ISSUE THREAD

**Issue by caspervdw** [caspervdw/pygeos#35]
For using coordinate-only functions in an efficient way we need something to convert any geometry array to 1D float arrays `x, y [,z]`.

Then we could use fast reprojections (pyproj) or affine transforms (scipy).

As a last step, the coordinates should be converted back to a geometry array (probably, using the old one as a template)

**Comment by jorisvandenbossche** [comment]
That was also on my to do list for the geopandas cython branch, for the use case you mention (pyproj), and potentially also for creating matplotlib collections.

For reconstructing the flat array of coordinates, we might need to output additional data? Eg an array offsets where each new geometry starts, and an array with the types (although for nested objects like polygons with exteriors and interiors, you also need to keep track of those).

**Comment by caspervdw** [comment]
To address that issue I was thinking of two functions. Say `arr` is your n-dimensional array filled with all kinds of geometries. Then:

```
x, y = get_coords(arr)
x2, y2 = reproject(x, y)
arr2 = set_coords(arr, x, y)
```

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/caspervdw/pygeos/pull/44
